[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
lazy_static = "1.5.0"
failure = "0.1.8"
rand = "0.8.5"

[[bin]]
name = "chess-engine"
path = "src/main.rs"