[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.8.0"
lazy_static = "1.5.0"
failure = "0.1.8"
rand = "0.8.5"
num_enum = "0.7.3"
round = "0.1.2"
once_cell="1.20.2"
criterion="0.5.1"
pprof = { version = "0.14.0", features = ["flamegraph"] }

[[bin]]
name = "chess-engine"
path = "src/main.rs"

[[bench]]
name = "my_benchmark"
harness = false